version: 3

vars:
  target: --target wasm32-unknown-unknown

tasks:
  default:
    cmd: task --list-all --sort none
    silent: true

  check:
    - task: check:up
    - task: check:down
    - bun run biome ci
    - bun run tsgo --project ./tsconfig.json

  check:*: cargo clippy -Zbuild-std=core {{.target}} -F {{index .MATCH 0}}

  build:
    - task: build:up
    - task: build:down

  build:*:
    vars:
      direction: '{{index .MATCH 0}}'
    env:
      RUSTFLAGS: -Cpanic=abort -Copt-level=z
    cmds:
      - cargo build -Zbuild-std=core --release {{.target}} -F {{.direction}}
      - wasm-opt -Oz --strip-producers --output ../target/migrate-{{.direction}}.wasm ../target/wasm32-unknown-unknown/release/vertx_config_migrate.wasm

  :*: cd .. && task {{index .MATCH 0}}
