name: Setup Node + pnpm
description: Setup Node + pnpm from versions config

inputs:
  install:
    description: Install dependencies
    default: 'true'
  packages:
    description: Additional global packages to install based on versions config
    default: ''

runs:
  using: composite
  steps:
    - id: node
      shell: bash
      run: .github/scripts/get-version.sh nodejs >> "$GITHUB_OUTPUT"
    - id: pnpm
      shell: bash
      run: .github/scripts/get-version.sh pnpm >> "$GITHUB_OUTPUT"
    - uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
      with:
        version: ${{ steps.pnpm.outputs.version }}
        run_install: false
    - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
      with:
        node-version: ${{ steps.node.outputs.version }}
        cache: pnpm
    - run: pnpm install
      shell: bash
      if: inputs.install == 'true'
    - shell: bash
      if: inputs.packages != ''
      env:
        PACKAGES: ${{ inputs.packages }}
      run: |
        IFS=','
        read -ra PACKAGES <<< "$PACKAGES"
        for package in "${PACKAGES[@]}"; do
          version="$(jq --raw-output ".\"$package\"" .config/versions.json)"
          if [[ -z "$version" ]]; then
            echo "$package is not in versions config"
            exit 1
          fi
          pnpm add --global "$package@$version"
        done
