version: 2
updates:
  - package-ecosystem: cargo
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      development:
        dependency-type: development
  - package-ecosystem: npm
    directory: 'vhs-web/'
    schedule:
      interval: 'monthly'
    groups:
      development:
        dependency-type: development
