version: 2
updates:
  - package-ecosystem: cargo
    directory: '/'
    schedule:
      interval: monthly
    groups:
      development:
        dependency-type: development
  - package-ecosystem: npm
    directory: 'vertx-configurator/'
    schedule:
      interval: monthly
    groups:
      development:
        dependency-type: development
  - package-ecosystem: devcontainers
    directory: '/'
    schedule:
      interval: monthly
