[package]
name = "vertx-server"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[features]
std = ["picoserve/std"]
serde = ["dep:serde", "heapless/serde"]

[dependencies]
edge-dhcp = { version = "0.2.0" }
embassy-futures = { workspace = true }
embassy-net = { workspace = true, features = ["log", "dhcpv4", "dhcpv4-hostname", "udp"] }
embassy-time = { workspace = true }
heapless = { workspace = true }
log = { workspace = true }
picoserve = { workspace = true, features = ["embassy"] }
serde = { workspace = true, features = ["derive"], optional = true }
vertx-network-hal = { workspace = true }

[build-dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = "=1.0.122"

[lints]
workspace = true
