savePrefix: ''

packages:
  - postcard-ts
  - vertx-config
  - vertx-configurator
  - vertx-simulator
  - scripts

onlyBuiltDependencies:
  - esbuild
  - sharp

overrides:
  lightningcss: npm:lightningcss-wasm@1.30.2
