version: 3

vars:
  nightly: nightly-2024-06-08

tasks:
  default:
    silent: true
    cmds:
      - task --list --sort none
      - echo
      - echo 'Any of these can be run from anywhere in the repo by prefixing it with a colon.'
      - "echo 'Eg: `task :fmt`'"

  setup:
    desc: Setup needed after first clone and dependency updates
    cmds:
      - git config --local include.path ../.config/git/config
      - rustup toolchain install {{.nightly}} --profile minimal --component rustfmt,clippy --target thumbv6m-none-eabi
      - cargo bin --install
      - cargo bin --sync-aliases
      - bun install
      - cd vertx-configurator && bun install
      - silent: true
        cmd: |
          echo
          echo 'Run `task target:set` to choose your hardware target'
          echo 'A complete list of targets can be printed by running `task set-target`'

  fmt:
    desc: Format everything
    cmds:
      - cargo +{{.nightly}} fmt --all
      - cargo bin dprint --config .config/dprint.json fmt
      - bun run biome format --config-path=.config/biome.json --write .

  clean:
    desc: Delete all build artifacts
    prompt: Delete all build artifacts?
    cmds:
      - cargo clean
      - cd vertx-configurator && rm -rf dist

  set-target:
    desc: Set the target to build for
    cmd: bun run scripts/set-target.ts
    silent: true

  "*/*":
    desc: Run a task from a subdirectory. The `vertx-` prefix can be dropped. (eg `task simulator:check`)
    vars:
      dir: "{{index .MATCH 0}}"
    cmd: cd {{if or (eq .dir "scripts") (hasPrefix "vertx" .dir)}}{{.dir}}{{else}}vertx-{{.dir}}{{end}} && task {{index .MATCH 1}}

  :*:
    - task: "{{index .MATCH 0}}"
