version: 3

dotenv:
  # Used to set defaults in set-target
  - out/target

tasks:
  default:
    silent: true
    cmds:
      - task --list --sort none
      - echo
      - echo 'Any of these can be run from anywhere in the repo by prefixing it with a colon.'
      - "echo 'Eg: `task :fmt`'"

  setup:
    desc: Setup needed after first clone and dependency updates
    cmds:
      - mise install
      - bun install
      - bun run scripts/fetch-rust.ts
      # Install dprint plugins:
      - .tools/bin/dprint output-file-paths --config=.config/dprint.json >/dev/null
      - silent: true
        cmd: echo && echo 'Run `task set-target` to choose your hardware target'

  fmt:
    desc: Format everything
    cmds:
      - cargo fmt --all
      - .tools/bin/dprint --config .config/dprint.json fmt
      - bun run biome format --config-path=.config/biome.json --write .

  clean:
    desc: Delete all build artifacts
    prompt: Delete all build artifacts?
    cmds:
      - rm -rf out
      - cargo clean
      - cd vertx-configurator && rm -rf dist .task
      - cd vertx-simulator && rm -rf dist .task

  set-target:
    desc: Set the target to build for
    cmd: bun run scripts/set-target.ts
    silent: true

  check-targets:
    desc: Validate all target specifications
    cmd: bun run scripts/check-targets.ts

  "*/*":
    desc: Run a task from a subdirectory. The `vertx-` prefix can be dropped. (eg `task simulator:check`)
    vars:
      dir: "{{index .MATCH 0}}"
    cmd: cd {{if or (eq .dir "scripts") (hasPrefix "vertx" .dir)}}{{.dir}}{{else}}vertx-{{.dir}}{{end}} && task {{index .MATCH 1}}

  :*:
    - task: "{{index .MATCH 0}}"
