version: 3

dotenv:
  - ../.env
  - .env
  - ../out/target

vars:
  simOutDir: out/simulator-firmware

tasks:
  default:
    silent: true
    cmds:
      - task --list-all --sort none
      - echo
      - echo 'Except for tasks starting with `simulator:`, all tasks require a target. This'
      - echo 'can be set by running `task target:set` in the root of the repo.'

  check: bun run ../scripts/build-target.ts --command=clippy {{.VERTX_TARGET}}
  build: bun run ../scripts/build-target.ts {{.VERTX_TARGET}}
  build:release: bun run ../scripts/build-target.ts {{.VERTX_TARGET}} --release

  flash: ../.tools/bin/probe-rs run --preverify --chip {{.VERTX_CHIP}} --idf-partition-table partitions.csv ../target/vertx

  simulator:edit:
    desc: Set up rust-analyzer config for supported editors for working on the simulator
    cmd: bun run ../scripts/set-ra-features.ts simulator

  simulator:check: bun run ../scripts/build-simulator.ts --command=clippy
  simulator:build: bun run ../scripts/build-simulator.ts
  simulator:build:release: bun run ../scripts/build-simulator.ts --release

  :*: cd .. && task {{index .MATCH 0}}
