version: 3

tasks:
  default:
    cmd: task --list-all --sort none
    silent: true

  check:
    - bun run biome ci .
    - task: check:tsc

  check:tsc:
    internal: true
    cmd: bun run tsc
    sources:
      - ../bun.lock
      - ../.config/tsconfig.*
      - src/**/*
      - tsconfig.*

  :*: cd .. && task {{index .MATCH 0}}
