version: 3

includes:
  embedded:
    taskfile: ../.config/tasks/Taskfile.embedded.yaml
    internal: true
    vars:
      chip: "{{.VERTX_BACKPACK_CHIP}}"

dotenv:
  - ../.env
  - .env
  - ../.env.target

tasks:
  default:
    cmds:
      - task --list-all --sort none
      - echo
      - echo 'Except for `check:*`, all tasks require a target with a backpack to be set using'
      - echo '`task set-target` in the repo root.'
    silent: true

  dbg:
    - task: embedded:dbg

  check:
    requires:
      vars: [VERTX_BACKPACK_CHIP]
    cmds:
      - task: embedded:cargo
        vars:
          command: clippy
          args: "{{.CLI_ARGS}}"

  check:*:
    desc: "Check a specific chip (e.g.: check:esp32)"
    cmds:
      - task: embedded:cargo
        vars:
          command: clippy
          chip: "{{index .MATCH 0}}"
          args: "{{.CLI_ARGS}}"

  build:
    requires:
      vars: [VERTX_BACKPACK_CHIP]
    cmds:
      - task: embedded:cargo
        vars:
          command: build
          args: "{{.CLI_ARGS}}"
      - task: post-build
        vars: { profile: debug }

  build:release:
    requires:
      vars: [VERTX_BACKPACK_CHIP]
    cmds:
      - task: embedded:cargo
        vars:
          command: build
          args: --release {{.CLI_ARGS}}
      - task: post-build
        vars: { profile: release }

  post-build:
    internal: true
    cmd: cp ../target/{{get (get .all_chip_data .VERTX_BACKPACK_CHIP) "target"}}/{{.profile}}/vertx-backpack ../target/vertx-backpack
    silent: true

  flash:
    - task: embedded:flash
      vars:
        flash: 2mb
        bin: ../target/vertx-backpack

  :*: cd .. && task {{index .MATCH 0}}
