name: cargo-install
description: cargo-install from mise

inputs:
  tool:
    description: Comma separated tool(s) to install
    required: true

runs:
  using: composite
  steps:
    - id: versions
      shell: bash
      env:
        TOOLS: ${{ inputs.tool }}
      run: |
        IFS=','
        read -ra TOOLS <<< "$TOOLS"
        declare -a output
        for tool in "${TOOLS[@]}"; do
          version="$(sed -En "s/.*\"cargo:$tool\"\s*=\s*\"([^\"]+)\".*/\1/p" .config/mise.toml)"
          if [[ -z "$version" ]]; then
            echo "$tool is not in mise config"
            exit 1
          fi
          output+=("$tool@$version")
        done
        echo "tools=${output[*]}" >> "$GITHUB_OUTPUT"
    - uses: taiki-e/install-action@9185c192a96ba09167ad8663015b3fbbf007ec79 # v2.56.2
      with:
        tool: ${{ steps.versions.outputs.tools }}
