name: cargo-install
description: cargo-install from .tool-versions

inputs:
  tool:
    description: Comma separated tool(s) to install
    required: true

runs:
  using: composite
  steps:
    - id: versions
      shell: bash
      env:
        TOOLS: ${{ inputs.tool }}
      run: |
        IFS=','
        read -ra TOOLS <<< "$TOOLS"
        declare -a output
        for tool in "${TOOLS[@]}"; do
          version="$(grep -E "^cargo:$tool\s" .tool-versions | awk '{print $2}')"
          if [[ -z "$version" ]]; then
            echo "$tool is not in .tool-versions"
            exit 1
          fi
          output+=("$tool@$version")
        done
        echo "tools=${output[*]}" >> "$GITHUB_OUTPUT"
    - uses: taiki-e/install-action@v2.52.6
      with:
        tool: ${{ steps.versions.outputs.tools }}
