name: cargo-install
description: cargo-install from version config

inputs:
  tool:
    description: Comma separated tool(s) to install
    required: true

runs:
  using: composite
  steps:
    - id: versions
      shell: bash
      env:
        TOOLS: ${{ inputs.tool }}
      run: |
        IFS=','
        read -ra TOOLS <<< "$TOOLS"
        declare -a output
        for tool in "${TOOLS[@]}"; do
          version="$(jq --raw-output ".\"$tool\"" .config/versions.json)"
          if [[ -z "$version" ]]; then
            echo "$tool is not in versions config"
            exit 1
          fi
          output+=("$tool@$version")
        done
        echo "tools=${output[*]}" >> "$GITHUB_OUTPUT"
    - uses: taiki-e/install-action@aa2649f25ee7099207734772f5393fd30167cb73
      with:
        tool: ${{ steps.versions.outputs.tools }}
