version: 3

tasks:
  cargo:
    requires:
      vars: [command, chip, rustcTarget]
    cmd: cargo {{.command}} -Zbuild-std=alloc,core --target {{.rustcTarget}} -F 'chip-{{.chip}}{{if .features}} {{.features}}{{end}}' {{.args}}

  flash:
    - task: flash:{{if hasPrefix "esp" .chip}}esp{{else}}probe-rs{{end}}
      vars:
        flash: { ref: .flash }
        bin: { ref: .bin }
  flash:esp: ../.tools/bin/espflash flash --baud 460800 --flash-size {{.flash}} --monitor {{.bin}}
  flash:probe-rs: ../.tools/bin/probe-rs run --chip {{.chip}} {{.bin}}
