version: 3

tasks:
  default:
    cmd: task --list-all --sort none
    silent: true

  check: cargo clippy {{.CLI_ARGS}}
  test: ../.tools/bin/cargo-nextest nextest run {{.CLI_ARGS}}

  :*: cd .. && task {{index .MATCH 0}}
