name = "vertx_mixer"
version = "0.1.0"
licences = ["MPL-2.0"]

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
nibble = ">= 1.1.3 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
argv = ">= 1.0.2 and < 2.0.0"
gleave = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
