version: 3

tasks:
  default:
    cmd: task --list-all --sort none
    silent: true

  check:
    - bun run biome ci .
    - task: check:tsc

  check:tsc:
    internal: true
    deps: [build:vertx]
    cmd: bun run tsc
    sources:
      - ../bun.lock
      - ../.config/tsconfig.*
      - src/**/*
      - '*.config.*'
      - tsconfig.*

  run:
    desc: Run a development server
    cmd: bun run vite

  build:
    env:
      NODE_ENV: production
    cmds:
      - task :configurator/simulator:build
      - task :vertx/simulator:build:release
      - task: check
      - bun run vite build
      - cp -r ../vertx-configurator/dist dist/configurator
    sources:
      - package.json
      - bun.lock
      - index.html
      - src/**/*
      - '*.config.*'
      - tsconfig.*
    generates:
      - dist/**/*

  build:vertx:
    internal: true
    cmd: task :vertx/simulator:build
    status:
      - test -f ../target/simulator/vertx.js

  preview:
    deps: [build]
    cmd: bun run vite preview

  :*: cd .. && task {{index .MATCH 0}}
