name: Setup Bun
description: Setup Bun using version from mise

inputs:
  install:
    description: Install dependencies
    default: 'true'

runs:
  using: composite
  steps:
    - id: version
      shell: bash
      run: |
        version="$(sed -En "s/.*\bbun\"?\s*=\s*\"([^\"]+)\".*/\1/p" .config/mise.toml)"
        if [[ -z "$version" ]]; then
          echo 'Bun is not in mise config'
          exit 1
        fi
        echo "bun=$version" >> "$GITHUB_OUTPUT"
    - uses: oven-sh/setup-bun@v2.0.2
      with:
        bun-version: ${{ steps.version.outputs.tools }}
    - run: bun install --frozen-lockfile
      shell: bash
      if: inputs.install == 'true'
