name: Setup Bun
description: Setup Bun using version from mise

inputs:
  install:
    description: Install dependencies
    default: 'true'

runs:
  using: composite
  steps:
    - id: version
      shell: bash
      run: .github/scripts/get-mise-version.sh bun >> "$GITHUB_OUTPUT"
    - uses: oven-sh/setup-bun@735343b667d3e6f658f44d0eca948eb6282f2b76 # v2.0.2
      with:
        bun-version: ${{ steps.version.outputs.version }}
    - run: bun install --frozen-lockfile
      shell: bash
      if: inputs.install == 'true'
