name: Setup Chip
description: Setup Rust toolchain, etc required for a specific chip

inputs:
  chip:
    description: Which chip to set up
    required: true

outputs:
  target:
    description: Rust target name
    value: ${{ steps.env.outputs.target }}

runs:
  using: composite
  steps:
    - id: env
      run: jq --raw-output '.xtensa as $xtensa | .chips.${{ inputs.chip }} | "xtensa=\($xtensa)\ntoolchain=\(.toolchain)\ntarget=\(.target)"' "$GITHUB_WORKSPACE/.config/toolchains.json" >> "$GITHUB_OUTPUT"
      shell: bash
    - if: steps.env.outputs.toolchain == 'xtensa'
      run: rm rust-toolchain.toml
      shell: bash
    - if: steps.env.outputs.toolchain == 'xtensa'
      uses: esp-rs/xtensa-toolchain@v1.5.3
      with:
        buildtargets: ${{ inputs.chip }}
        default: true
        ldproxy: false
        version: ${{ steps.env.outputs.xtensa }}
