version: 3

tasks:
  default:
    cmd: task --list-all --sort none
    silent: true

  check:
    cmds:
      - bun run biome ci
      - bun run tsgo --project ./tsconfig.json

  :*: cd .. && task {{index .MATCH 0}}
