version: 3

includes:
  embedded:
    taskfile: ../.config/tasks/Taskfile.embedded.yaml
    internal: true

tasks:
  default:
    cmd: task --list-all --sort none
    silent: true

  check:esp32:
    - task: check-impl
      vars:
        chip: esp32
        rustcTarget: xtensa-esp32-none-elf

  check:esp32c3:
    - task: check-impl
      vars:
        chip: esp32c3
        rustcTarget: riscv32imc-unknown-none-elf

  check:esp32s3:
    - task: check-impl
      vars:
        chip: esp32s3
        rustcTarget: xtensa-esp32s3-none-elf

  check-impl:
    internal: true
    cmds:
      - task: embedded:cargo
        vars:
          command: clippy
          chip: "{{.chip}}"
          rustcTarget: "{{.rustcTarget}}"
          args: "{{.CLI_ARGS}}"

  :*: cd .. && task {{index .MATCH 0}}
