version: 3

tasks:
  default:
    cmd: task --list-all --sort none
    silent: true

  check:
    - bun run biome ci .
    - task: check:tsc

  check:tsc:
    internal: true
    cmd: bun run tsc
    sources:
      - ../bun.lockb
      - ../.config/tsconfig.*
      - scripts/**/*
      - src/**/*
      - '*.config.*'
      - tsconfig.*

  build:
    - task: cache:native
    - task: build-impl
      vars:
        target: native
    - task: build:compress

  run:
    desc: Run a development server
    env:
      VITE_TARGET: native
    cmd: bun run vite

  preview:
    deps: [build]
    cmd: bun run vite preview

  build-impl:
    internal: true
    deps: [check]
    env:
      NODE_ENV: production
      VITE_TARGET: '{{.target}}'
    cmd: bun run vite build
    sources:
      - package.json
      - bun.lockb
      - index.html
      - src/**/*
      - '*.config.*'
      - tsconfig.*
      - scripts/compress.ts
      - dist/.taskCacheKey

  build:compress:
    internal: true
    cmd: bun run scripts/compress.ts
    status:
      - ls dist | grep -q '\.gz$'

  simulator:build:
    cmds:
      - task: cache:simulator
      - task: build-impl
        vars:
          target: simulator

  simulator:run:
    env:
      VITE_TARGET: simulator
    cmd: bun run vite

  cache:*:
    cmd: mkdir -p dist && echo {{.MATCH}} > dist/.taskCacheKey
    internal: true
    silent: true

  :*: cd .. && task {{index .MATCH 0}}
