version: 3

tasks:
  default:
    cmd: task --list-all --sort none
    silent: true

  check:
    - bun run biome ci .
    - task: check:astro
    - bun run tsgo --project ./tsconfig.json

  check:astro:
    internal: true
    cmd: bun run astro check
    sources:
      - ../bun.lock
      - ../.config/tsconfig.*
      - src/**/*
      - '*.config.*'
      - tsconfig.*

  run:
    desc: Run a development server for use with simulator/run
    env:
      VERTX_SIMULATOR: true
    cmd: bun run astro dev

  build:
    - task: build:native
    - task: build:post

  preview:
    deps: [build]
    cmd: bun run astro preview

  build:*:
    internal: true
    deps: [check]
    env:
      NODE_ENV: production
      VERTX_SIMULATOR: '{{eq (index .MATCH 0) "simulator"}}'
    cmds:
      - bun run astro build
      - bun run scripts/prune.ts

  build:post:
    internal: true
    cmd: bun run scripts/post-build.ts
    status:
      - ls ../out/configurator | grep -q '\.gz$'

  simulator:build:
    cmds:
      - task: build:simulator

  :*: cd .. && task {{index .MATCH 0}}
