version: 3

tasks:
  default:
    cmd: task --list-all --sort none
    silent: true

  check:
    - bun run biome ci .
    - task: check:astro
    - task: check:tsc

  check:astro:
    internal: true
    cmd: bun run astro check
    sources:
      - ../bun.lock
      - ../.config/tsconfig.*
      - src/**/*
      - '*.config.*'
      - tsconfig.*

  check:tsc:
    internal: true
    cmd: bun run tsc
    sources:
      - ../bun.lock
      - ../.config/tsconfig.*
      - scripts/**/*
      - tsconfig.*

  run:
    desc: Run a development server for use with simulator/run
    env:
      VERTX_SIMULATOR: true
    cmd: bun run astro dev

  build:
    - task: cache:native
    - task: build-impl
      vars:
        simulator: false
    - task: build:post

  preview:
    deps: [build]
    cmd: bun run astro preview

  build-impl:
    internal: true
    deps: [check]
    env:
      NODE_ENV: production
      VERTX_SIMULATOR: '{{.simulator}}'
    cmds:
      - bun run astro build
      - bun run scripts/prune.ts
    sources:
      - ../bun.lock
      - src/**/*
      - '*.config.*'
      - tsconfig.*
      - scripts/*
      - dist/.taskCacheKey

  build:post:
    internal: true
    cmd: bun run scripts/post-build.ts
    status:
      - ls dist | grep -q '\.gz$'

  simulator:build:
    cmds:
      - task: cache:simulator
      - task: build-impl
        vars:
          simulator: true

  cache:*:
    cmd: mkdir -p dist && echo {{.MATCH}} > dist/.taskCacheKey
    internal: true
    silent: true

  :*: cd .. && task {{index .MATCH 0}}
