version: 3

tasks:
  default:
    cmd: task --list-all --sort none
    silent: true

  check:
    cmds:
      - bun run biome ci
      - bun run tsgo --project ./tsconfig.json

  codegen:
    cmds:
      - rm -rf out && mkdir out
      - bun run src/generate.ts
      - rustfmt --config-path ../rustfmt.toml out/config.rs out/current.rs out/old.rs
      - bun run biome format --write out/config.ts
      - sha512sum config.ts config.old.ts src/**.ts > out/.hashes
    status:
      - sha512sum --status --check out/.hashes

  :*: cd .. && task {{index .MATCH 0}}
