version: 3

tasks:
  default:
    cmd: task --list-all --sort none
    silent: true

  check:
    cmds:
      - bun run biome ci *.ts
      - task: check:tsc

  check:tsc:
    internal: true
    cmds:
      - bun run tsc
    sources:
      - ../.config/tsconfig.*
      - tsconfig.*
      - '*.ts'

  run:
    vars:
      rust: out/config.rs
      typescript: out/config.ts
    cmds:
      - rm -rf out && mkdir out
      - bun run generate.ts {{.rust}} {{.typescript}}
      - rustfmt --edition 2021 {{.rust}}
      - bun run biome format --config-path=../.config/biome.json --write {{.typescript}}
    sources:
      - '*.ts'
    generates:
      - 'out/*'

  :*: cd .. && task {{index .MATCH 0}}
