version: 3

tasks:
  default:
    cmd: task --list-all --sort none
    silent: true

  check:
    cmds:
      - bun run biome ci *.ts
      - task: check:tsc

  check:tsc:
    internal: true
    cmds:
      - bun run tsc
    sources:
      - ../.config/tsconfig.*
      - tsconfig.*
      - '*.ts'

  codegen:
    cmds:
      - rm -rf out && mkdir out
      - bun run generate.ts
      - rustfmt --edition 2021 out/config.rs out/current.rs out/old.rs
      - bun run biome format --config-path=../.config/biome.json --write out/config.ts
    sources:
      - '*.ts'
    generates:
      - 'out/*'

  :*: cd .. && task {{index .MATCH 0}}
