name: Update dependencies

# Requirements:
# - secret containing a personal access token with r/w permissions for contents & PRs
# - deploy key with write permissions
# - secret containing above private key
# - variable containing the GitHub public ssh keys

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:
    inputs:
      dry-run:
        description: Dry run
        type: boolean
        default: false

permissions:
  contents: read

jobs:
  updates:
    name: Update dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Git identity
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
      - uses: ./.github/actions/setup-rust
      - uses: asdf-vm/actions/setup@v3
      - name: Install asdf plugins
        run: |
          asdf plugin add actionlint https://github.com/crazy-matt/asdf-actionlint
          asdf plugin add bun https://github.com/cometkim/asdf-bun
          asdf plugin add task https://github.com/particledecay/asdf-task
          asdf plugin add typos https://github.com/aschiavon91/asdf-typos
      - run: asdf install bun
      - name: Install dependencies
        run: bun install --frozen-lockfile
      - run: bun run scripts/update.ts
      - name: Show full diff
        run: git diff ${{ github.ref_name }}
      - name: Push updates
        if: github.ref == 'refs/heads/main' || inputs.dry-run
        run: |
          mkdir -p "$HOME/.ssh"
          echo '${{ vars.GH_SSH_PUB_KEYS }}' >> "$HOME/.ssh/known_hosts"
          echo '${{ secrets.UPDATES_SSH_KEY }}' >> "$HOME/.ssh/id_updates"
          chmod -R 600 "$HOME/.ssh/id_updates"
          eval "$(ssh-agent -s)"
          ssh-add "$HOME/.ssh/id_updates"
          git remote set-url origin git@github.com:${{ github.repository }}.git
          git push --set-upstream origin updates
      - name: Open PR
        if: github.ref == 'refs/heads/main' || inputs.dry-run
        run: gh pr create --base main --title 'Update dependencies' --body-file '.updates.md'
        env:
          GH_TOKEN: ${{ secrets.UPDATES_TOKEN }}
