chip = "rp2040"

[status]
type = "ws2812"
pin = 6

[sd]
type = "spi"
spi = "SPI1"
cs = 7
sclk = 10
mosi = 11
miso = 12

[ui]
up = 0
down = 1
right = 2
left = 3

[display]
driver = "ssd1306"
i2c = "I2C0"
sda = 8
scl = 9
