chip = "esp32s3"

[pins]
leds = 38
sd = 3
analog = [4, 5, 6, 7]
switches = [11]

[pins.spi]
sclk = 12
mosi = 13
miso = 14

[pins.ui]
up = 15
down = 16
right = 17
left = 18

[pins.display]
type = 'ssd1306'
sda = 8
scl = 9
