chip = "esp32s3"

leds.status = 38
# analog = [4, 5, 6, 7]
# switches = [11]

[sd]
type = "spi"
cs = 7

[spi]
sclk = 12
mosi = 13
miso = 14

[ui]
up = 15
down = 16
right = 17
left = 18

[display]
type = "ssd1306"
sda = 8
scl = 9
