chip = "esp32s3"

# analog = [4, 5, 6, 7]
# switches = [11]

[status]
type = "ws2812"
pin = 38

[sd]
type = "spi"
cs = 7
sclk = 12
mosi = 13
miso = 14

[ui]
up = 15
down = 16
right = 17
left = 18

[display]
driver = "ssd1306"
sda = 8
scl = 9
