chip = "rp2040"

[pins]
leds = 6
sd = 7
analog = []
switches = []

[pins.spi]
sclk = 10
mosi = 11
miso = 12

[pins.ui]
up = 0
down = 1
right = 2
left = 3

[pins.display]
type = 'ssd1306'
sda = 8
scl = 9
