[package]
name = "vertx-network-hal"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
embassy-net-driver = "=0.2.0"
heapless = { workspace = true }

[lints]
workspace = true
